
# to list from command: `ros2 param dump /map_analyzer --print`
map_analyzer:  # /map_analyzer or map_analyzer are both acceptable
  ros__parameters:
    candidates_radius_num: 100
    candidates_pixel_step: 2
    convolution_size: 9
    map_topic: 'map'
    odom_topic: 'odom'
    use_sim_time: True

    # int_array:
    # - 10
    # - 11
    # str_array:
    # - 'str1'
    # - 'str2'

    # nested_param:
    #   another_byte_array:
    #   - 0x0A
    #   - 0x0B
    #   another_int: 101